###############################################################################
# FAULT - Profiles
#
# Valid profile range: 400 - 499
###############################################################################

profiles:
  - profile:
      id: 400
      transitions:
        auto_transition_on: false
        auto_transition_profile:
        fault_transition_on: false
        fault_transition_profile: 400

      processes: []

  - profile:
      id: 401
      transitions:
        auto_transition_on: false
        auto_transition_profile:
        fault_transition_on: false
        fault_transition_profile: 400

      processes: []
